Check text
hr-js/project_cat pull request #8
Opened 2017-07-09 13:26 UTC by minako-nakanishi

文字数制御・空文字で送信時のエラー表示です。
ご査収の程宜しくお願い致します。

2017-07-09 13:45 UTC, ikkyu-3 requested changes

2017-07-09 13:45 UTC, ikkyu-3 commented on src/main.js
> +     }else {
ここのif文の処理は、128文字より大きくなったらエラー文字を表示させる処理となっています。

本来の目的は文字数の制御なので、

129文字以上入力させない => 128文字に強制的に変換する = 文字入力の制御
という処理が必要かと思います。

...今更気がついたんですが、<textarea>の属性の「maxlength」で制御すればよくねって気がつきました。。
属性埋めたら一発で終わるけど、勉強でJSで制御してみるのも面白いかも...

2017-07-09 13:49 UTC, t-tonchim reviewed
ざっと気になったところをコメントしました。

2017-07-09 13:49 UTC, tomoyuki-tanaka commented on src/main.js
> +       return;
この`return`何も返さないのなら不要ではないでしょうか。

2017-07-09 13:49 UTC, tomoyuki-tanaka commented on src/main.js
> +       var lengthError = document.getElementById('error_text');
`var`と`let`が混在していますね。基本的には`const`で宣言して再代入が必要な場合のみ`let`を使うのが良いです。

2017-07-09 13:49 UTC, tomoyuki-tanaka commented on src/main.js
> +     let sliceMsg = messages.slice();
この`slice()`は意味がないのではないでしょうか？引数に何も渡さなければmessagesと同じ値になると思います。

2017-07-09 13:49 UTC, tomoyuki-tanaka commented on src/main.js
> +     }else {
else節で何もしないならば不要ですね。今後実装するのであれば`// TODO: ~~を実装する` のようにコメントするとレビュアーに優しいですよ。

2017-07-09 13:49 UTC, tomoyuki-tanaka commented on src/main.js
> +    if(sliceMsg.length >128 ){
この場合は`>`ではなくて`<`にすれば良いのではないでしょうか。また128はマジックコメントなので定数として定義しておくのが良いと思います。

2017-07-09 13:49 UTC, tomoyuki-tanaka commented on src/main.js
> +    countMsg(); //文字数制御
文字数制御ではなくてカウントではないですか？どちらにせよ関数名とコメントが異なると混乱を招きますので注意しましょう。また関数名から想像できるような処理ならコメントしなくて良いと思います。
カウントだとするとここで呼び出した場合は動的に変化しませんが問題ないですか？ inputイベントの時に呼び出すのが良いと思います。

2017-07-10 15:22 UTC, ikkyu-3 approved these changes
修正確認しましたー！大丈夫です！ありがとうございます！

2017-07-10 15:24 UTC, ikkyu-3 commented
明日ぐらいにマージして、masterにmergeしようと思います。その際、少しコメントつけたり、varを使わないなど、簡単な修正はする予定です。

2017-07-11 13:19 UTC, merged